# Stage 1: Build Frontend
FROM node:18 as frontend-build

WORKDIR /apps

# Use a reliable npm registry mirror
RUN npm config set registry https://registry.npmmirror.com

# Install dependencies
COPY package*.json /apps/
RUN npm install

# Copy frontend source files
COPY apps/frontend /apps/frontend
RUN npm run build --prefix /apps/frontend

# Stage 2: Build Backend
FROM node:18 as backend-build

WORKDIR /apps

# Reuse the npm registry mirror
RUN npm config set registry https://registry.npmmirror.com

# Install dependencies
COPY package*.json /apps/
RUN npm install

# Copy backend source files
COPY apps/backend /apps/backend
RUN npm run build --prefix /apps/backend

# Final Stage
FROM node:18

WORKDIR /apps
COPY --from=frontend-build /apps/frontend/dist /apps/frontend/dist
COPY --from=backend-build /apps/backend/dist /apps/backend/dist

EXPOSE 3000 5000
CMD ["sh", "-c", "npm run start:backend & npm run start:frontend && wait"]
